#!/bin/bash
#
#   purpose: Capture image/video from Raspberry Pi Camera or USB Camera	
#    author: Robert C. Burkhall
#      date: June 7, 2015
#
#license(s): http://www.gnu.org/licenses/agpl.txt
#
# credit(s): 
#
#

if [ "$1" == "" ]; then
	echo "Capture video or stills"
	echo "     -v : Video Capture from PiCamera"
	echo "     -s : Still Capture from PiCamera"
	echo "     -us : Still Capture from USB Camera"
	echo "     -uv : Still Capture from USB Camera"
elif [ "$1" == "-s" ]; then
	# Capture an image from the camera
	raspistill -vf -hf  -o cam-$(date +"%Y-%m-%d_%H%M").jpg
elif [ "$1" == "-v" ]; then 
	# Capture video	
	raspivid -t 5000 -o video.h264 -b 3500000
elif [ "$1" == "-us" ]; then
	# Capture still from USB
	fswebcam -p YUYV -d /dev/video0 -r 640x480 ucam-$(date +"%Y-%m-%d_%H%M").jpg
fi
